### ISSUE TITLE
isim soyisim vs gerekmeksizin tc validasyonu

### ISSUE THREAD

**Issue by sahin52** [aaydin-tr/tcvalidator#1]
Sadece TC numarası verilerek tc validasyonu yapılabilmeli diye düşünüyorum.

**Comment by aaydin-tr** [comment]
Sadece TC ile maalesef mümkün değil çünkü bu servis direk bakanlığın servisi ile haberleşiyor doğrulamayı bakanlığı servisi yapıyor, fakat TC'yi sadece patern ile de kontrol edebilirsiniz fakat bu kişi hakkında kesin doğruluk vermez.
